### ISSUE TITLE
PHP Fatal error: calling $page on the homepage causes the website to crash

### ISSUE THREAD

**Issue by Janybanny** [bludit-themes/massively#6]
I just tried to use the Massively theme with Bludit 3.14.1 and PHP 7.4 and it gave me this error:

```
[09-Nov-2022 19:23:28] WARNING: [pool www] child 13525 said into stderr: "[09-Nov-2022 19:23:28 Europe/Vienna] PHP Fatal error:  Uncaught Error: Call to a member function permalink() on bool in /var/www/virtual/jany/html/bl-themes/massively-2.1/index.php:55"
[09-Nov-2022 19:23:28] WARNING: [pool www] child 13525 said into stderr: "Stack trace:"
[09-Nov-2022 19:23:28] WARNING: [pool www] child 13525 said into stderr: "#0 /var/www/virtual/jany/html/bl-kernel/boot/site.php(26): include()"
[09-Nov-2022 19:23:28] WARNING: [pool www] child 13525 said into stderr: "#1 /var/www/virtual/jany/html/index.php(41): require('/var/www/virtua...')"
[09-Nov-2022 19:23:28] WARNING: [pool www] child 13525 said into stderr: "#2 {main}"
[09-Nov-2022 19:23:28] WARNING: [pool www] child 13525 said into stderr: "  thrown in /var/www/virtual/jany/html/bl-themes/massively-2.1/index.php on line 55"
```

It only crashes on the homepage (https://janybanny.moe) and not on static subpages (f.e. https://janybanny.moe/about). The error only comes up when loading the homepage.

It also only happens with the massively theme installed and not other themes that I've tried, which is why I am submitting it here

I found out that it fails in this line (55) at the `$page->permalink()` function, because it seems to have no $page (since it's the homepage and not a post or static site/user content).

```
<li class="<?php echo ($staticPage->permalink()==$page->permalink())?'active':'' ?>"><a href="<?php echo $staticPage->permalink() ?>#main"><?php echo $staticPage->title() ?></a></li>
```

I sadly don't know enough php to fix this, so help is appreciated

**Comment by clickwork-git** [comment]
What is the configuration of the homepage? Posts or a static page?

**Comment by Janybanny** [comment]
The homepage is just the main page that lists all the posts afaik. I never worked with bludit, but used the same theme ported to ghost before and there it just listed all the posts (currently none) and has links to static sites in the bar (at the bottom of the page). You can load the about page to see a post, it looks the same, but there is no post, just a list of posts that were published.
I don't know what this is called/how this works exactly in bludit

**Comment by Janybanny** [comment]
It basically calls this variable, but fails because it returns false.

https://docs.bludit.com/en/developers/predefined-variables#page

I will try and add an if statement before to check if it returns false and it should theoretically work afterwards

**Comment by Janybanny** [comment]
I solved the issue by adding a post. The theme breaks on multiple locations if there are no regular posts on the site. I'll close this issue with that, since I won't develop a fix and I don't expect anyone else to do so (it's a very niche issue), but if anyone wants to fix it, feel free to reopen it.
